POST http://localhost:8080/api/events HTTP/1.1
X-Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdDIiLCJ1aWQiOiI2MTcwODU2OWNiYzk0Yzk5OTRmNTI2NjUiLCJpYXQiOjE2MzUzNTc1OTgsImV4cCI6MTYzNTM2NDc5OH0.BheuyK2Qh4Y--JuIPMtaxaMzTEcjAGABFuG-A2_dXHg
Content-Type: application/json

{
  "title": "New event 3",
  "description": "Test event 3",
  "start": 10000000,
  "end": 20000000
}