DELETE http://localhost:8080/api/events/0456 HTTP/1.1
X-Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTcwN2NjNGNhM2JhZTYxYTdmYjlhZGYiLCJuYW1lIjoidGVzdDEiLCJpYXQiOjE2MzQ4NTIxNDYsImV4cCI6MTYzNDg1OTM0Nn0.hE8znKPA8rPGJF8L2OBPxKdWzp4om3nIS4hkmNb18CE