GET http://localhost:8080/api/events HTTP/1.1
X-Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTcwN2NjNGNhM2JhZTYxYTdmYjlhZGYiLCJuYW1lIjoidGVzdDEiLCJpYXQiOjE2MzQ5MDg2MzYsImV4cCI6MTYzNDkxNTgzNn0.FD6MWZj1WljooE3udE6nnF-Hmxy0TJgS7VeMZjPMcKo